### ISSUE TITLE
Which loss is used to update the parameters of the attention mechanism?

### ISSUE THREAD

**Issue by xihuai18** [caslab-vt/SARNet#1]
Hello! I wonder which loss is used to update the parameters of the attention mechanism, the policy gradient loss or the value function loss? I can't figure it out from the code.

**Comment by murtazarang** [comment]
It's the policy gradient loss, since the attention mechanism is trained as part of the policy network.

However, for the attention mechanism in the critic, (if using the MAAC type critic), the training is through the value function.
