### ISSUE TITLE
still cannot reproduce the results

### ISSUE THREAD

**Issue by PaladinEE15** [caslab-vt/SARNet#4]
I update my repository and run the following commands :
python train.py --policy-grad reinforce --env-type ic3net --scenario traffic_junction --num_adversaries 6 --key-units 32 --value-units 32 --query-units 32 --len-traj-update 10 --encoder-model LSTM --max-episode-len 20 --add_rate_min 0.3
and get bad results:
......
steps: 468000, episodes: 23400.0, mean episode success: 0.409841880341                                                                                                         8804, time: 718.005
steps: 472000, episodes: 23600.0, mean episode success: 0.411190677966                                                                                                         1017, time: 724.915
steps: 476000, episodes: 23800.0, mean episode success: 0.412306722689                                                                                                         07564, time: 731.739
steps: 480000, episodes: 24000.0, mean episode success: 0.413377083333                                                                                                         33334, time: 738.46
...Finished total of 24010.0 episodes.

I update the codes to tf2 so there might be bugs. Could you please show me your output?

**Comment by murtazarang** [comment]
Closing this issue and continuing it on the main thread created earlier.

[https://github.com/caslab-vt/SARNet/issues/3](https://github.com/caslab-vt/SARNet/issues/3)
